# Generated by Django 4.0 on 2022-01-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank='True', null=True, upload_to='profiles/avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='background',
            field=models.ImageField(blank='True', null=True, upload_to='profiles/background'),
        ),
    ]
