# Generated by Django 4.0 on 2022-01-20 19:36

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_profile_avatar_alter_profile_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, height_field=1, null=True, upload_to=registration.models.custom_upload_to_avatar, width_field=1),
        ),
    ]
