# Generated by Django 4.0 on 2021-12-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
    ]
