# Generated by Django 4.0 on 2021-12-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_task_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glue_color', models.CharField(max_length=150)),
                ('content_color', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='dashboard.task')),
            ],
        ),
    ]
