# Generated by Django 4.0 on 2021-12-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_taskcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcolor',
            name='color',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
